language: java
env:
  - PLAY_VERSION=2.2.2
before_script:
  - wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script: "cd code && ../play-${PLAY_VERSION}/play test publish-local && cd ../sample && ../play-${PLAY_VERSION}/play compile"
